### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by DarkDBx** [DarkDBx/LittleHelper-D4#1]
### TODO

- [x] gui: logging console and transparency
- [x] toolbox: image, rgb color and macro recorder
- [x] assistant: improve behavior and scanning

- [ ] #3

**Comment by DarkDBx** [comment]
combat: improve behavior and scanning
pickit: nip parser for property scan
pathing: path creator with layout scan for dungeons
